# Generated by Django 6.0.6 on 2026-09-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_lesson_created_by_profile_last_active_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Unpublished (draft) lessons are hidden from Students.'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Unpublished (draft) quizzes are hidden from Students.'),
        ),
    ]
