# Generated by Django 5.2.17 on 2026-10-08 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_terms(apps, schema_editor):
    """Publish Terms v1.0 so the system works right after migrating. Existing
    students will be asked to accept it the next time they log in."""
    from myapp.terms_text import TERMS_V1_TITLE, TERMS_V1_CONTENT
    TermsVersion = apps.get_model('myapp', 'TermsVersion')
    if not TermsVersion.objects.exists():
        TermsVersion.objects.create(
            version='1.0', title=TERMS_V1_TITLE, content=TERMS_V1_CONTENT, requires_reacceptance=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_quiz_created_at_quiz_deadline_datetime_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar_flag_reason",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar_flagged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=60)),
                ("details", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_targets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TermsVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                (
                    "title",
                    models.CharField(default="Terms and Conditions", max_length=120),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="One rule per heading. Blank line = new paragraph."
                    ),
                ),
                ("requires_reacceptance", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_terms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="TermsAcceptance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_acceptances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptances",
                        to="myapp.termsversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-accepted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "terms"),
                        name="one_acceptance_per_user_per_version",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_terms, migrations.RunPython.noop),
    ]
