# Generated by Django 5.2.17 on 2026-10-08 06:35

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


def make_default_classrooms(apps, schema_editor):
    """Every Mentor (and anyone who already created lessons/quizzes) gets one
    classroom, and their existing lessons and quizzes move into it so nothing
    disappears. Students then join a classroom with its code."""
    import secrets
    Classroom = apps.get_model('myapp', 'Classroom')
    Lesson = apps.get_model('myapp', 'Lesson')
    Quiz = apps.get_model('myapp', 'Quiz')
    Profile = apps.get_model('myapp', 'Profile')
    alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
    used = set(Classroom.objects.values_list('code', flat=True))

    def new_code():
        while True:
            c = ''.join(secrets.choice(alphabet) for _ in range(7))
            if c not in used and any(ch.isalpha() for ch in c):
                used.add(c)
                return c

    owner_ids = set(Profile.objects.filter(role='MENTOR').values_list('user_id', flat=True))
    owner_ids |= set(Lesson.objects.exclude(created_by=None).values_list('created_by_id', flat=True))
    owner_ids |= set(Quiz.objects.exclude(created_by=None).values_list('created_by_id', flat=True))

    User = apps.get_model('auth', 'User')
    rooms = {}
    for user in User.objects.filter(pk__in=owner_ids).order_by('pk'):
        prof = Profile.objects.filter(user_id=user.pk).first()
        label = ((prof.name if prof else '') or '').strip() or user.username
        rooms[user.pk] = Classroom.objects.create(
            name=f"{label}'s Classroom", mentor_id=user.pk, code=new_code(),
        )

    for uid, room in rooms.items():
        Lesson.objects.filter(created_by_id=uid, classroom=None).update(classroom=room)
        Quiz.objects.filter(created_by_id=uid, classroom=None).update(classroom=room)
    # A quiz with no owner follows the lesson it is linked to.
    for quiz in Quiz.objects.filter(classroom=None).exclude(lesson=None).select_related('lesson'):
        if quiz.lesson.classroom_id:
            Quiz.objects.filter(pk=quiz.pk).update(classroom_id=quiz.lesson.classroom_id)


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_terms_consent_photo_review_audit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "code",
                    models.CharField(
                        default=myapp.models.generate_unique_code,
                        editable=False,
                        max_length=12,
                        unique=True,
                    ),
                ),
                (
                    "code_enabled",
                    models.BooleanField(
                        default=True, help_text="Turn off to stop new students joining."
                    ),
                ),
                ("code_updated_at", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classrooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="myapp.classroom",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="myapp.classroom",
            ),
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="myapp.classroom",
                    ),
                ),
                (
                    "removed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["student__username"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("classroom", "student"),
                        name="one_enrollment_per_student_per_classroom",
                    )
                ],
            },
        ),
        migrations.RunPython(make_default_classrooms, migrations.RunPython.noop),
    ]
