# Generated by Django 5.2.17 on 2026-10-08 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_classrooms"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="account_status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="deactivation_reason",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="quiz",
            name="allow_late_submissions",
            field=models.BooleanField(
                default=False,
                help_text="If ticked, students can still submit after the deadline (marked Late).",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="deadline_at_submission",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FinalWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open (student has time to act)"),
                            ("RESOLVED", "Resolved (no action needed)"),
                            ("PENDING_REVIEW", "Waiting for Admin review"),
                            ("DEACTIVATED", "Account deactivated"),
                            ("RESET", "Reset by staff"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("activity", models.CharField(blank=True, default="", max_length=60)),
                (
                    "resolution_note",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "quizzes",
                    models.ManyToManyField(
                        related_name="final_warnings", to="myapp.quiz"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_warnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="AccountStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=12)),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                ("details", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="myapp.finalwarning",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("REMINDER", "Deadline reminder"),
                            ("OVERDUE", "Overdue quiz"),
                            ("FINAL_WARNING", "Final warning"),
                            ("DEACTIVATED", "Account deactivated"),
                            ("REACTIVATED", "Account reactivated"),
                            ("ACCOMMODATION", "Extension / exemption"),
                            ("ADMIN_ALERT", "Admin alert"),
                        ],
                        max_length=16,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("hidden", models.BooleanField(default=False)),
                ("dedupe_key", models.CharField(max_length=160, unique=True)),
                (
                    "email_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("NO_EMAIL", "No email address"),
                            ("NOT_SENT", "Not emailed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "email_error",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("email_attempts", models.PositiveIntegerField(default=0)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="myapp.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warning",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="myapp.finalwarning",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PolicySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_hours",
                    models.CharField(
                        blank=True,
                        default="24,2",
                        help_text="Hours before a deadline to remind students, separated by commas. Empty = no reminders.",
                        max_length=60,
                    ),
                ),
                ("send_overdue_email", models.BooleanField(default=True)),
                (
                    "warn_threshold",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="A final warning is issued when a student has this many unresolved overdue quizzes.",
                    ),
                ),
                (
                    "warn_after_overdue_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="...and the oldest overdue quiz has been overdue at least this many hours.",
                    ),
                ),
                (
                    "warning_window_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="How long a student has to act after a final warning (minimum 24).",
                    ),
                ),
                (
                    "deactivate_min_unresolved",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="After the window, deactivate only if at least this many warned quizzes are still unresolved.",
                    ),
                ),
                (
                    "auto_deactivation_approved",
                    models.BooleanField(
                        default=False,
                        help_text="OFF: after the window the case waits for an Admin to review. ON: the system deactivates automatically.",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizAccommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("EXTENSION", "Extension"),
                            ("EXEMPTION", "Exemption"),
                        ],
                        max_length=10,
                    ),
                ),
                ("new_deadline", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="myapp.quiz",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_accommodations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("quiz", "student"),
                        name="one_accommodation_per_student_per_quiz",
                    )
                ],
            },
        ),
    ]
