# Generated by Django 5.2.17 on 2026-10-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_deadlines_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="student_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=30
            ),
        ),
    ]
